services:
  client:
    build: ./
    container_name: client_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./postcss.config.ts:/app/postcss.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./eslint.config.js:/app/eslint.config.js
      - ./.env:/app/.env
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
